baseURL = "https://clericpy.github.io/blog/"
languageCode = "en-us"
title = "Clericpy's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
publishDir = "docs"
googleAnalytics = "UA-150991415-1"

[author]
  name = "Clericpy"
  homepage = "https://github.com/ClericPy"

[languages]
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Clericpy's Blog"
disqus = "clericpy"
description = "Hello world?"
favicon = "/blog/favicon.ico"
googleAnalytics = "UA-150991415-1"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-150991415-1"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag("js", new Date());  gtag("config", "UA-150991415-1");</script>'

[[params.socials]]
name = "Categories"
link = "/blog/categories/"

[[params.socials]]
name = "Issue"
link = "https://github.com/ClericPy/blog/issues"

[[params.socials]]
name = "RSS"
link = "/blog/index.xml"

[[params.socials]]
name = "News"
link = "https://www.clericpy.top/newspaper/articles.query.html"

[[params.socials]]
name = "About"
link = "/blog/about"
