baseURL = "https://clericpy.github.io/blog/"
languageCode = "en-us"
title = "Clericpy's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
publishDir = "docs"

[author]
  name = "Clericpy"
  homepage = "https://github.com/ClericPy"

[languages]
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Clericpy's Blog"
disqus = "clericpy"
description = "Hello world?"
extraHead = ""
favicon = "favicon.ico"

[[params.socials]]
name = "RSS"
link = "/blog/index.xml"

[[params.socials]]
name = "Theme"
link = "https://github.com/joway/hugo-theme-yinyang"

[[params.socials]]
name = "Newspaper"
link = "https://www.clericpy.top/newspaper/articles.query.html"

[[params.socials]]
name = "Github"
link = "https://github.com/ClericPy"
